version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project-management-api
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    depends_on:
      - postgres
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=3000
      - JWT_SECRET=${JWT_SECRET}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=${DB_USERNAME:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_DATABASE=${DB_DATABASE:-projectmgmt}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - SES_EMAIL_FROM=${SES_EMAIL_FROM}
      - SNS_TASK_NOTIFICATIONS_TOPIC=${SNS_TASK_NOTIFICATIONS_TOPIC}
    volumes:
      - ./logs:/app/logs
    networks:
      - app-network

  postgres:
    image: postgres:14-alpine
    container_name: postgres-db
    restart: unless-stopped
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_DATABASE:-projectmgmt}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
